# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x12silvertongue.agent\"\x9c\x01\n\x13StartSessionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0c\n\x04mode\x18\x03 \x01(\t\x12\x12\n\nuser_level\x18\x04 \x01(\t\x12\r\n\x05topic\x18\x05 \x01(\t\x12\x18\n\x10\x63ontext_file_url\x18\x06 \x01(\t\x12\x15\n\ractive_skills\x18\x07 \x03(\t\">\n\x14StartSessionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"\x84\x01\n\x11\x43hatStreamRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x13\n\x0b\x61udio_chunk\x18\x02 \x01(\x0c\x12\x16\n\x0eis_final_chunk\x18\x03 \x01(\x08\x12\x14\n\x0c\x65nergy_level\x18\x04 \x01(\x02\x12\x18\n\x10silence_duration\x18\x05 \x01(\x02\"\xbb\x01\n\x12\x43hatStreamResponse\x12\x12\n\ntext_delta\x18\x01 \x01(\t\x12\x13\n\x0b\x61udio_chunk\x18\x02 \x01(\x0c\x12\x13\n\x0bis_finished\x18\x03 \x01(\x08\x12\x38\n\tchinglish\x18\x04 \x01(\x0b\x32%.silvertongue.agent.ChinglishAnalysis\x12\x14\n\x0crefined_text\x18\x05 \x01(\t\x12\x17\n\x0fuser_transcript\x18\x06 \x01(\t\"j\n\x11\x43hinglishAnalysis\x12\x15\n\rhas_chinglish\x18\x01 \x01(\x08\x12\x18\n\x10original_pattern\x18\x02 \x01(\t\x12\x12\n\nsuggestion\x18\x03 \x01(\t\x12\x10\n\x08severity\x18\x04 \x01(\t\"A\n\x12ScaffoldingRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x17\n\x0fincomplete_text\x18\x02 \x01(\t\"/\n\x13ScaffoldingResponse\x12\x18\n\x10\x63ompletion_hints\x18\x01 \x03(\t2\xb5\x02\n\x0c\x41gentService\x12\x61\n\x0cStartSession\x12\'.silvertongue.agent.StartSessionRequest\x1a(.silvertongue.agent.StartSessionResponse\x12_\n\nChatStream\x12%.silvertongue.agent.ChatStreamRequest\x1a&.silvertongue.agent.ChatStreamResponse(\x01\x30\x01\x12\x61\n\x0eGetScaffolding\x12&.silvertongue.agent.ScaffoldingRequest\x1a\'.silvertongue.agent.ScaffoldingResponseB+\n\x1b\x63om.silvertongue.grpc.agentB\nAgentProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.silvertongue.grpc.agentB\nAgentProtoP\001'
  _globals['_STARTSESSIONREQUEST']._serialized_start=36
  _globals['_STARTSESSIONREQUEST']._serialized_end=192
  _globals['_STARTSESSIONRESPONSE']._serialized_start=194
  _globals['_STARTSESSIONRESPONSE']._serialized_end=256
  _globals['_CHATSTREAMREQUEST']._serialized_start=259
  _globals['_CHATSTREAMREQUEST']._serialized_end=391
  _globals['_CHATSTREAMRESPONSE']._serialized_start=394
  _globals['_CHATSTREAMRESPONSE']._serialized_end=581
  _globals['_CHINGLISHANALYSIS']._serialized_start=583
  _globals['_CHINGLISHANALYSIS']._serialized_end=689
  _globals['_SCAFFOLDINGREQUEST']._serialized_start=691
  _globals['_SCAFFOLDINGREQUEST']._serialized_end=756
  _globals['_SCAFFOLDINGRESPONSE']._serialized_start=758
  _globals['_SCAFFOLDINGRESPONSE']._serialized_end=805
  _globals['_AGENTSERVICE']._serialized_start=808
  _globals['_AGENTSERVICE']._serialized_end=1117
# @@protoc_insertion_point(module_scope)
