# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub:
    """智能体交互服务 - Spring Boot 调用 Python Agent
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartSession = channel.unary_unary(
                '/silvertongue.agent.AgentService/StartSession',
                request_serializer=agent__pb2.StartSessionRequest.SerializeToString,
                response_deserializer=agent__pb2.StartSessionResponse.FromString,
                _registered_method=True)
        self.ChatStream = channel.stream_stream(
                '/silvertongue.agent.AgentService/ChatStream',
                request_serializer=agent__pb2.ChatStreamRequest.SerializeToString,
                response_deserializer=agent__pb2.ChatStreamResponse.FromString,
                _registered_method=True)
        self.GetScaffolding = channel.unary_unary(
                '/silvertongue.agent.AgentService/GetScaffolding',
                request_serializer=agent__pb2.ScaffoldingRequest.SerializeToString,
                response_deserializer=agent__pb2.ScaffoldingResponse.FromString,
                _registered_method=True)


class AgentServiceServicer:
    """智能体交互服务 - Spring Boot 调用 Python Agent
    """

    def StartSession(self, request, context):
        """开启 AI 对练会话
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatStream(self, request_iterator, context):
        """语音对话流 (双向流传输音频及状态)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScaffolding(self, request, context):
        """卡壳时的引导式表达补全
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=agent__pb2.StartSessionRequest.FromString,
                    response_serializer=agent__pb2.StartSessionResponse.SerializeToString,
            ),
            'ChatStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=agent__pb2.ChatStreamRequest.FromString,
                    response_serializer=agent__pb2.ChatStreamResponse.SerializeToString,
            ),
            'GetScaffolding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScaffolding,
                    request_deserializer=agent__pb2.ScaffoldingRequest.FromString,
                    response_serializer=agent__pb2.ScaffoldingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'silvertongue.agent.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('silvertongue.agent.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService:
    """智能体交互服务 - Spring Boot 调用 Python Agent
    """

    @staticmethod
    def StartSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/silvertongue.agent.AgentService/StartSession',
            agent__pb2.StartSessionRequest.SerializeToString,
            agent__pb2.StartSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/silvertongue.agent.AgentService/ChatStream',
            agent__pb2.ChatStreamRequest.SerializeToString,
            agent__pb2.ChatStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScaffolding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/silvertongue.agent.AgentService/GetScaffolding',
            agent__pb2.ScaffoldingRequest.SerializeToString,
            agent__pb2.ScaffoldingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
