# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: assessment.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'assessment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61ssessment.proto\x12\x17silvertongue.assessment\"I\n\rAssessRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\naudio_data\x18\x02 \x01(\x0c\x12\x13\n\x0btarget_text\x18\x03 \x01(\t\"\x96\x01\n\x0e\x41ssessResponse\x12\x13\n\x0b\x66inal_score\x18\x01 \x01(\x02\x12\x10\n\x08\x61\x63\x63uracy\x18\x02 \x01(\x02\x12\x0f\n\x07\x66luency\x18\x03 \x01(\x02\x12\x14\n\x0c\x63ompleteness\x18\x04 \x01(\x02\x12\x36\n\x05words\x18\x05 \x03(\x0b\x32\'.silvertongue.assessment.WordAssessment\"g\n\x0eWordAssessment\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x38\n\x08phonemes\x18\x03 \x03(\x0b\x32&.silvertongue.assessment.PhonemeDetail\"U\n\rPhonemeDetail\x12\x0f\n\x07phoneme\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x12\n\nstart_time\x18\x03 \x01(\x01\x12\x10\n\x08\x65nd_time\x18\x04 \x01(\x01\" \n\x10\x43hinglishRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"c\n\x11\x43hinglishResponse\x12\x15\n\rhas_chinglish\x18\x01 \x01(\x08\x12\x37\n\x08patterns\x18\x02 \x03(\x0b\x32%.silvertongue.assessment.ErrorPattern\"H\n\x0c\x45rrorPattern\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x12\n\nerror_text\x18\x02 \x01(\t\x12\x12\n\nsuggestion\x18\x03 \x01(\t2\xe5\x01\n\x11\x41ssessmentService\x12\x66\n\x13\x41ssessPronunciation\x12&.silvertongue.assessment.AssessRequest\x1a\'.silvertongue.assessment.AssessResponse\x12h\n\x0f\x44\x65tectChinglish\x12).silvertongue.assessment.ChinglishRequest\x1a*.silvertongue.assessment.ChinglishResponseB5\n com.silvertongue.grpc.assessmentB\x0f\x41ssessmentProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'assessment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.silvertongue.grpc.assessmentB\017AssessmentProtoP\001'
  _globals['_ASSESSREQUEST']._serialized_start=45
  _globals['_ASSESSREQUEST']._serialized_end=118
  _globals['_ASSESSRESPONSE']._serialized_start=121
  _globals['_ASSESSRESPONSE']._serialized_end=271
  _globals['_WORDASSESSMENT']._serialized_start=273
  _globals['_WORDASSESSMENT']._serialized_end=376
  _globals['_PHONEMEDETAIL']._serialized_start=378
  _globals['_PHONEMEDETAIL']._serialized_end=463
  _globals['_CHINGLISHREQUEST']._serialized_start=465
  _globals['_CHINGLISHREQUEST']._serialized_end=497
  _globals['_CHINGLISHRESPONSE']._serialized_start=499
  _globals['_CHINGLISHRESPONSE']._serialized_end=598
  _globals['_ERRORPATTERN']._serialized_start=600
  _globals['_ERRORPATTERN']._serialized_end=672
  _globals['_ASSESSMENTSERVICE']._serialized_start=675
  _globals['_ASSESSMENTSERVICE']._serialized_end=904
# @@protoc_insertion_point(module_scope)
